name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/messaging_app:${{ github.sha }} messaging_app
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging_app:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/messaging_app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/messaging_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging_app:latest
