# Generated by Django 5.2.4 on 2025-07-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_rename_edited_message_is_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='edited',
        ),
    ]
